from mcr.microsoft.com/dotnet/core/sdk:3.1
run apt update
run apt install -y python3 python3-pip ipython3
run pip3 install numpy matplotlib pandas scipy networkx community IPython
run mkdir /codigo
workdir /codigo
CMD /bin/bash